package service

import "errors"

var (
	ErrAuthRequestNotFound                    = errors.New("auth request not found")
	ErrAuthRequestExpired                     = errors.New("auth request expired")
	ErrInvalidMasterApprovalSignature         = errors.New("invalid master approval signature")
	ErrMasterIdentityNotFound                 = errors.New("master identity not found")
	ErrMasterKeyRevoked                       = errors.New("master key revoked")
	ErrMasterEncPubMismatch                   = errors.New("master_enc_pub mismatch")
	ErrMasterIDMismatch                       = errors.New("master_id mismatch")
	ErrKeyringUpdateRequired                  = errors.New("keyring_update required for first master")
	ErrInvalidMasterID                        = errors.New("invalid master_id")
	ErrMasterIdentityExists                   = errors.New("master identity already exists")
	ErrMachineAlreadyBound                    = errors.New("machine already bound to another master")
	ErrMachineRevoked                         = errors.New("machine revoked")
	ErrUnknownMachine                         = errors.New("unknown machine")
	ErrInvalidAction                          = errors.New("invalid action")
	ErrKeyringUpdateConflict                  = errors.New("keyring update conflict")
	ErrSignerMasterKeyNotFound                = errors.New("signer master key not found")
	ErrInvalidKeyringUpdateSignature          = errors.New("invalid keyring update signature")
	ErrMasterKeyAlreadyExists                 = errors.New("master key already exists")
	ErrMasterKeyNotFoundForRevoke             = errors.New("master key not found for revoke")
	ErrKeyringUpdateMasterIDMissing           = errors.New("missing keyring_update.master_id")
	ErrKeyringUpdateMasterIDMismatch          = errors.New("keyring_update.master_id mismatch")
	ErrKeyringUpdateSeqInvalid                = errors.New("keyring_update.seq must be 1")
	ErrKeyringUpdatePrevHashInvalid           = errors.New("keyring_update.prev_hash must be empty")
	ErrKeyringUpdateActionInvalid             = errors.New("keyring_update.action must be add")
	ErrKeyringUpdateTargetMasterSignMismatch  = errors.New("keyring_update.target_master_sign_pub mismatch")
	ErrKeyringUpdateTargetMasterEncMismatch   = errors.New("keyring_update.target_master_enc_pub mismatch")
	ErrKeyringUpdateSignerFingerprintMismatch = errors.New("keyring_update.signer_master_sign_key_fingerprint mismatch")

	ErrInvalidConnectToken      = errors.New("invalid connect_token")
	ErrInvalidMachineToken      = errors.New("invalid machine_token")
	ErrInvalidMachineAccessToken = errors.New("invalid machine_access_token")
	ErrTokenExpired             = errors.New("token expired")
	ErrMachineBusy          = errors.New("machine already has an active session")
	ErrMachineNotConnected  = errors.New("machine not connected")
	ErrUnauthorizedMachine  = errors.New("machine does not belong to master identity")
	ErrUnauthorizedSession  = errors.New("unauthorized session")
	ErrInvalidSessionInit   = errors.New("invalid session-init")
	ErrInvalidTokenFormat   = errors.New("invalid token format")
	ErrInvalidRequest       = errors.New("invalid request")
)
