import { expect, test } from "@playwright/test";

test("opens a workspace from the shell and drills into task detail", async ({ page }) => {
  await page.goto("/");

  await expect(page.getByTestId("workspace-picker-button")).toBeEnabled();
  page.once("dialog", (dialog) => dialog.accept("/tmp/muxagent-workspace"));
  await page.getByTestId("workspace-picker-button").click();

  await expect(page.getByTestId("entry-shell")).toBeVisible();
  await expect(page.getByTestId("board-card-task-live-fixture")).toContainText(
    "Refactor auth middleware",
  );

  await page.getByTestId("board-card-task-live-fixture").click();

  await expect(page).toHaveURL(/\/workspaces\/[^/]+\/tasks\/task-live-fixture$/);
  await expect(page.getByTestId("task-detail-screen")).toBeVisible();
  await expect(page.getByText("Refactor auth middleware")).toBeVisible();
  await expect(page.getByText("Output · implement")).toBeVisible();
});

test("task deep links restore the route workspace even after switching to another workspace", async ({
  page,
}) => {
  await page.goto("/");

  await expect(page.getByTestId("workspace-picker-button")).toBeEnabled();
  page.once("dialog", (dialog) => dialog.accept("/tmp/muxagent-workspace"));
  await page.getByTestId("workspace-picker-button").click();

  await expect(page.getByTestId("board-card-task-live-fixture")).toBeVisible();
  await page.getByTestId("board-card-task-live-fixture").click();
  await expect(page).toHaveURL(/\/workspaces\/[^/]+\/tasks\/task-live-fixture$/);
  const firstWorkspaceDetailPath = new URL(page.url()).pathname;
  await expect(
    page.locator(".shell-workspace__row.is-active .shell-workspace__label").first(),
  ).toContainText(
    "muxagent-workspace",
  );

  await page.goBack();
  await expect(page).toHaveURL(/\/$/);
  await expect(page.getByTestId("entry-shell")).toBeVisible();
  await expect(page.getByTestId("workspace-picker-button")).toBeEnabled();
  page.once("dialog", (dialog) => dialog.accept("/tmp/muxagent-alt-workspace"));
  await page.getByTestId("workspace-picker-button").click();
  await expect(page.getByTestId("board-card-task-live-fixture")).toBeVisible();
  await expect(
    page.locator(".shell-workspace__row.is-active .shell-workspace__label").first(),
  ).toContainText("muxagent-alt-workspace");

  await page.evaluate((pathname) => {
    window.history.pushState({}, "", pathname);
    window.dispatchEvent(new PopStateEvent("popstate"));
  }, firstWorkspaceDetailPath);

  await expect(page).toHaveURL(new RegExp(`${firstWorkspaceDetailPath}$`));
  await expect(page.getByTestId("task-detail-screen")).toBeVisible();
  await expect(
    page.locator(".shell-workspace__row.is-active .shell-workspace__label").first(),
  ).toContainText(
    "muxagent-workspace",
  );
});

test("renders approval and artifact preview task surfaces", async ({ page }) => {
  await page.goto("/");

  await expect(page.getByTestId("workspace-picker-button")).toBeEnabled();
  page.once("dialog", (dialog) => dialog.accept("/tmp/muxagent-workspace"));
  await page.getByTestId("workspace-picker-button").click();

  await page.getByTestId("board-card-task-awaiting-pr").click();
  await expect(page.getByTestId("approval-pane")).toBeVisible();
  await expect(page.getByText("Review PR #42")).toBeVisible();
  await expect(page.getByRole("button", { name: "Approve" })).toBeVisible();

  await page.goBack();
  await expect(page).toHaveURL(/\/$/);
  await page.getByTestId("board-card-task-live-fixture").click();
  await page.getByRole("button", { name: "plan.md plan" }).click();
  await expect(page.getByTestId("artifact-pane")).toBeVisible();
  await expect(page.getByText("Fixture artifact generated by the desktop web bridge.")).toBeVisible();
});

test("renders failed and complete task surfaces", async ({ page }) => {
  await page.goto("/");

  await expect(page.getByTestId("workspace-picker-button")).toBeEnabled();
  page.once("dialog", (dialog) => dialog.accept("/tmp/muxagent-workspace"));
  await page.getByTestId("workspace-picker-button").click();

  await page.getByTestId("board-card-task-failed-deploy").click();
  await expect(page.getByTestId("failed-pane")).toBeVisible();
  await expect(
    page.getByTestId("failed-pane").getByText("Health check failed after deploy"),
  ).toBeVisible();

  await page.goBack();
  await expect(page).toHaveURL(/\/$/);
  await page.getByTestId("board-card-task-done-login").click();
  await expect(page.getByTestId("complete-pane")).toBeVisible();
  await expect(page.getByTestId("complete-pane").getByText("Task completed")).toBeVisible();
});
