// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/LaLanMo/muxagent-relay/internal/config"
	"github.com/LaLanMo/muxagent-relay/internal/ioc"
	"github.com/LaLanMo/muxagent-relay/internal/repository"
	"github.com/LaLanMo/muxagent-relay/internal/repository/dao"
	"github.com/LaLanMo/muxagent-relay/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config) (*App, error) {
	db, err := ioc.InitDB(cfg)
	if err != nil {
		return nil, err
	}
	authRequestDAO := dao.NewGormAuthRequestDAO(db)
	authRequestRepository := repository.NewAuthRequestRepository(authRequestDAO)
	masterIdentityDAO := dao.NewGormMasterIdentityDAO(db)
	masterIdentityRepository := repository.NewMasterIdentityRepository(masterIdentityDAO)
	masterKeyDAO := dao.NewGormMasterKeyDAO(db)
	masterKeyRepository := repository.NewMasterKeyRepository(masterKeyDAO)
	machineDAO := dao.NewGormMachineDAO(db)
	machineRepository := repository.NewMachineRepository(machineDAO)
	keyringUpdateDAO := dao.NewGormKeyringUpdateDAO(db)
	keyringUpdateRepository := repository.NewKeyringUpdateRepository(keyringUpdateDAO)
	txRunner := repository.NewTxRunner(db)
	relaySigningKey, err := ioc.InitRelaySigningKey()
	if err != nil {
		return nil, err
	}
	privateKey := ioc.RelaySignPrivate(relaySigningKey)
	publicKey := ioc.RelaySignPublic(relaySigningKey)
	authService := service.NewAuthService(authRequestRepository, masterIdentityRepository, masterKeyRepository, machineRepository, keyringUpdateRepository, txRunner, privateKey, publicKey)
	authHandler := ioc.InitAuthHandler(authService, cfg)
	keyringService := service.NewKeyringService(masterIdentityRepository, masterKeyRepository, keyringUpdateRepository, txRunner)
	keyringHandler := ioc.InitKeyringHandler(keyringService)
	tokenService := service.NewTokenService(masterKeyRepository, machineRepository)
	wsHub := service.NewWSHub()
	sessionRegistry := service.NewSessionRegistry()
	deviceTokenDAO := dao.NewGormDeviceTokenDAO(db)
	deviceTokenRepository := repository.NewDeviceTokenRepository(deviceTokenDAO)
	app := ioc.InitFirebaseApp(cfg)
	client := ioc.InitFCMClient(app)
	pushService := service.NewPushService(deviceTokenRepository, client)
	wsServiceConfig := ioc.InitWSServiceConfig(cfg)
	wsService := service.NewWSService(machineRepository, masterKeyRepository, tokenService, wsHub, sessionRegistry, pushService, wsServiceConfig)
	wsConnLimiter := ioc.InitWSConnLimiter(cfg)
	wsHandler := ioc.InitWSHandler(wsService, wsConnLimiter)
	deviceHandler := ioc.InitDeviceHandler(tokenService, deviceTokenRepository)
	tokenAuthMiddleware := ioc.InitTokenAuthMiddleware(tokenService)
	engine, err := ioc.SetupRouter(authHandler, keyringHandler, wsHandler, deviceHandler, tokenAuthMiddleware, cfg, db)
	if err != nil {
		return nil, err
	}
	v := ioc.InitAuthCleanup(authService)
	mainApp := &App{
		Router:      engine,
		AuthCleanup: v,
	}
	return mainApp, nil
}

// wire.go:

var daoSet = wire.NewSet(dao.NewGormAuthRequestDAO, dao.NewGormMasterIdentityDAO, dao.NewGormMasterKeyDAO, dao.NewGormMachineDAO, dao.NewGormKeyringUpdateDAO, dao.NewGormDeviceTokenDAO)

var repositorySet = wire.NewSet(repository.NewAuthRequestRepository, repository.NewMasterIdentityRepository, repository.NewMasterKeyRepository, repository.NewMachineRepository, repository.NewKeyringUpdateRepository, repository.NewDeviceTokenRepository, repository.NewTxRunner)

var serviceSet = wire.NewSet(service.NewWSHub, service.NewSessionRegistry, service.NewTokenService, service.NewWSService, service.NewAuthService, service.NewKeyringService, service.NewPushService, ioc.InitWSServiceConfig)

var handlerSet = wire.NewSet(ioc.InitAuthHandler, ioc.InitKeyringHandler, ioc.InitWSHandler, ioc.InitDeviceHandler)

var middlewareSet = wire.NewSet(ioc.InitWSConnLimiter, ioc.InitTokenAuthMiddleware)

var routerSet = wire.NewSet(ioc.SetupRouter)
