// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package intergration

import (
	"github.com/LaLanMo/muxagent-relay/internal/ioc"
	"github.com/LaLanMo/muxagent-relay/internal/repository"
	"github.com/LaLanMo/muxagent-relay/internal/repository/dao"
	"github.com/LaLanMo/muxagent-relay/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitTestContainer() (*testContainer, error) {
	intergrationTestDBBundle, err := initTestDB()
	if err != nil {
		return nil, err
	}
	db := intergrationTestDBBundle.DB
	authRequestDAO := dao.NewGormAuthRequestDAO(db)
	authRequestRepository := repository.NewAuthRequestRepository(authRequestDAO)
	masterIdentityDAO := dao.NewGormMasterIdentityDAO(db)
	masterIdentityRepository := repository.NewMasterIdentityRepository(masterIdentityDAO)
	masterKeyDAO := dao.NewGormMasterKeyDAO(db)
	masterKeyRepository := repository.NewMasterKeyRepository(masterKeyDAO)
	machineDAO := dao.NewGormMachineDAO(db)
	machineRepository := repository.NewMachineRepository(machineDAO)
	keyringUpdateDAO := dao.NewGormKeyringUpdateDAO(db)
	keyringUpdateRepository := repository.NewKeyringUpdateRepository(keyringUpdateDAO)
	txRunner := repository.NewTxRunner(db)
	relaySigningKey, err := initTestRelaySigningKey()
	if err != nil {
		return nil, err
	}
	privateKey := ioc.RelaySignPrivate(relaySigningKey)
	publicKey := ioc.RelaySignPublic(relaySigningKey)
	authService := service.NewAuthService(authRequestRepository, masterIdentityRepository, masterKeyRepository, machineRepository, keyringUpdateRepository, txRunner, privateKey, publicKey)
	authHandler := initTestAuthHandler(authService)
	keyringService := service.NewKeyringService(masterIdentityRepository, masterKeyRepository, keyringUpdateRepository, txRunner)
	keyringHandler := ioc.InitKeyringHandler(keyringService)
	tokenService := service.NewTokenService(masterKeyRepository, machineRepository)
	wsHub := service.NewWSHub()
	sessionRegistry := service.NewSessionRegistry()
	deviceTokenDAO := dao.NewGormDeviceTokenDAO(db)
	deviceTokenRepository := repository.NewDeviceTokenRepository(deviceTokenDAO)
	client := initTestNilFCMClient()
	pushService := service.NewPushService(deviceTokenRepository, wsHub, client)
	config := initTestConfig()
	wsServiceConfig := ioc.InitWSServiceConfig(config)
	wsService := service.NewWSService(machineRepository, masterKeyRepository, tokenService, wsHub, sessionRegistry, pushService, wsServiceConfig)
	wsConnLimiter := ioc.InitWSConnLimiter(config)
	wsHandler := ioc.InitWSHandler(wsService, wsConnLimiter)
	deviceHandler := ioc.InitDeviceHandler(tokenService, deviceTokenRepository)
	tokenAuthMiddleware := ioc.InitTokenAuthMiddleware(tokenService)
	engine, err := ioc.SetupRouter(authHandler, keyringHandler, wsHandler, deviceHandler, tokenAuthMiddleware, config, db)
	if err != nil {
		return nil, err
	}
	testCleanup := intergrationTestDBBundle.Cleanup
	intergrationTestContainer := &testContainer{
		Router:         engine,
		DB:             db,
		AuthService:    authService,
		KeyringService: keyringService,
		RelayPriv:      privateKey,
		RelayPub:       publicKey,
		Cleanup:        testCleanup,
	}
	return intergrationTestContainer, nil
}

// wire.go:

var testInfraSet = wire.NewSet(
	initTestDB, wire.FieldsOf(new(*testDBBundle), "DB", "Cleanup"), initTestRelaySigningKey,
	initTestConfig, ioc.RelaySignPrivate, ioc.RelaySignPublic,
)

var testDaoSet = wire.NewSet(dao.NewGormAuthRequestDAO, dao.NewGormMasterIdentityDAO, dao.NewGormMasterKeyDAO, dao.NewGormMachineDAO, dao.NewGormKeyringUpdateDAO, dao.NewGormDeviceTokenDAO)

var testRepositorySet = wire.NewSet(repository.NewAuthRequestRepository, repository.NewMasterIdentityRepository, repository.NewMasterKeyRepository, repository.NewMachineRepository, repository.NewKeyringUpdateRepository, repository.NewDeviceTokenRepository, repository.NewTxRunner)

var testServiceSet = wire.NewSet(service.NewWSHub, service.NewSessionRegistry, service.NewTokenService, service.NewWSService, service.NewAuthService, service.NewKeyringService, initTestNilFCMClient, service.NewPushService, ioc.InitWSServiceConfig)

var testHandlerSet = wire.NewSet(
	initTestAuthHandler, ioc.InitKeyringHandler, ioc.InitWSHandler, ioc.InitDeviceHandler, ioc.InitWSConnLimiter, ioc.InitTokenAuthMiddleware,
)

// Use production SetupRouter so rate-limit middleware and SetTrustedProxies
// validation are exercised by integration tests.
var testRouterSet = wire.NewSet(ioc.SetupRouter)
