// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package intergration

import (
	"github.com/LaLanMo/muxagent-relay/internal/ioc"
	"github.com/LaLanMo/muxagent-relay/internal/repository"
	"github.com/LaLanMo/muxagent-relay/internal/repository/dao"
	"github.com/LaLanMo/muxagent-relay/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitTestContainer() (*testContainer, error) {
	db, cleanup, err := initTestDB()
	if err != nil {
		return nil, err
	}
	authRequestDAO := dao.NewGormAuthRequestDAO(db)
	authRequestRepository := repository.NewAuthRequestRepository(authRequestDAO)
	masterIdentityDAO := dao.NewGormMasterIdentityDAO(db)
	masterIdentityRepository := repository.NewMasterIdentityRepository(masterIdentityDAO)
	masterKeyDAO := dao.NewGormMasterKeyDAO(db)
	masterKeyRepository := repository.NewMasterKeyRepository(masterKeyDAO)
	machineDAO := dao.NewGormMachineDAO(db)
	machineRepository := repository.NewMachineRepository(machineDAO)
	keyringUpdateDAO := dao.NewGormKeyringUpdateDAO(db)
	keyringUpdateRepository := repository.NewKeyringUpdateRepository(keyringUpdateDAO)
	txRunner := repository.NewTxRunner(db)
	relaySigningKey, err := initTestRelaySigningKey()
	if err != nil {
		cleanup()
		return nil, err
	}
	privateKey := ioc.RelaySignPrivate(relaySigningKey)
	publicKey := ioc.RelaySignPublic(relaySigningKey)
	authService := service.NewAuthService(authRequestRepository, masterIdentityRepository, masterKeyRepository, machineRepository, keyringUpdateRepository, txRunner, privateKey, publicKey)
	authHandler := initTestAuthHandler(authService)
	keyringService := service.NewKeyringService(masterIdentityRepository, masterKeyRepository, keyringUpdateRepository, txRunner)
	keyringHandler := ioc.InitKeyringHandler(keyringService)
	deviceTokenDAO := dao.NewGormDeviceTokenDAO(db)
	deviceTokenRepository := repository.NewDeviceTokenRepository(deviceTokenDAO)
	wsHub := service.NewWSHub()
	sessionRegistry := service.NewSessionRegistry()
	tokenService := service.NewTokenService(masterKeyRepository)
	fcmClient := initTestNilFCMClient()
	pushService := service.NewPushService(deviceTokenRepository, wsHub, fcmClient)
	wsService := service.NewWSService(machineRepository, masterKeyRepository, tokenService, wsHub, sessionRegistry, pushService)
	wsHandler := ioc.InitWSHandler(wsService)
	engine := initTestRouter(authHandler, keyringHandler, wsHandler)
	testContainer := &testContainer{
		Router:         engine,
		DB:             db,
		AuthService:    authService,
		KeyringService: keyringService,
		RelayPriv:      privateKey,
		RelayPub:       publicKey,
		Cleanup:        cleanup,
	}
	return testContainer, nil
}

// wire.go:

var testInfraSet = wire.NewSet(initTestDB, initTestRelaySigningKey, ioc.RelaySignPrivate, ioc.RelaySignPublic)

var testDaoSet = wire.NewSet(dao.NewGormAuthRequestDAO, dao.NewGormMasterIdentityDAO, dao.NewGormMasterKeyDAO, dao.NewGormMachineDAO, dao.NewGormKeyringUpdateDAO, dao.NewGormDeviceTokenDAO)

var testRepositorySet = wire.NewSet(repository.NewAuthRequestRepository, repository.NewMasterIdentityRepository, repository.NewMasterKeyRepository, repository.NewMachineRepository, repository.NewKeyringUpdateRepository, repository.NewDeviceTokenRepository, repository.NewTxRunner)

var testServiceSet = wire.NewSet(service.NewWSHub, service.NewSessionRegistry, service.NewTokenService, service.NewWSService, service.NewAuthService, service.NewKeyringService, initTestNilFCMClient, service.NewPushService)

var testHandlerSet = wire.NewSet(initTestAuthHandler, ioc.InitKeyringHandler, ioc.InitWSHandler)

var testRouterSet = wire.NewSet(initTestRouter)
